### ISSUE TITLE
User Auth, Styling Review

### ISSUE THREAD

**Issue by jonbirke0927** [rlim92/meep#2]
App is looking great so far! Just a few comments on styling below.

1. For the purple buttons (i.e. "Get Started"), have the color transition be a bit more gradual, as it is on the real site
2. For the purple buttons (i.e. "Get Started"), have the font size / type be closer to that of the real site
3. For login / signup input boxes, upon a failed login / signup, the input boxes should have a red border and background 

Keep up the great progress!

**Comment by rlim92** [comment]
Hey Jon!
1. i got a gradual transition of 0.5sec on hover and unhover
2. I'm having a lot of trouble getting the font to look exactly the same because i think its a proprietary Slack font. do you have any tips for custom fonts?
3. I added a red border on error did u want a red background as well? 

Thanks for the feedback!

**Comment by jonbirke0927** [comment]
Hey Rich,

2. Matching fonts can be tricky, if that's as close as you can get it, no problem. Maybe take a look at the resource Kai sent to the circle channel if you haven't already.
3. I'd also add the light red background, just want the errors to look as close to the real site as possible.

**Comment by rlim92** [comment]
Hey Jon,

2. I'll continue to look as i progress!
3. Got the light red background!

Thanks! have a good weekend
